import type { FieldIr } from "./types.js";

export const GENERATED_BANNER = "// Generated by @mattiasahlsen/zodql codegen. Do not edit.";

/**
 * The header every managed file carries.
 *
 * The schema's content hash lives in the manifest rather than here, so editing
 * the schema doesn't rewrite the first line of every file in the output.
 */
export function banner(schemaSource: string): string {
  return [GENERATED_BANNER, `// Source: ${schemaSource}`, "/* eslint-disable */"].join("\n");
}

/** A comment terminator inside a description would end the JSDoc block early. */
function escapeComment(text: string): string {
  return text.replaceAll("*/", "*\\/");
}

/**
 * Render a JSDoc block, or nothing when there's nothing to say.
 *
 * Prettier reflows these, so the emitter doesn't try to wrap them itself.
 */
export function jsDoc(parts: readonly (string | undefined)[]): string {
  const lines = parts
    .filter((part): part is string => part !== undefined && part.trim() !== "")
    .flatMap((part) => escapeComment(part).split("\n"));

  if (lines.length === 0) return "";
  if (lines.length === 1) return `/** ${lines[0]} */`;
  return ["/**", ...lines.map((line) => ` * ${line}`.trimEnd()), " */"].join("\n");
}

/** The JSDoc for one pick property: description, deprecation, and argument hint. */
export function fieldDoc(field: FieldIr): string {
  const argHint =
    field.args.length > 0
      ? `@remarks Arguments: ${field.args
          .map((arg) => `\`${arg.name}: ${arg.type}\``)
          .join(", ")}. Attach them with \`zodqlField().withArguments(...)\` around this field's selection.`
      : undefined;

  return jsDoc([
    field.description,
    field.deprecationReason === undefined ? undefined : `@deprecated ${field.deprecationReason}`,
    argHint === undefined ? undefined : (field.description ?? field.deprecationReason) ? `\n${argHint}` : argHint,
  ]);
}

/** A string literal safe to embed in generated source. */
export function quote(value: string): string {
  return JSON.stringify(value);
}

/** Prefix each line of a block, skipping blank lines. */
export function indent(block: string, prefix = "  "): string {
  return block
    .split("\n")
    .map((line) => (line === "" ? line : `${prefix}${line}`))
    .join("\n");
}

/** Attach a JSDoc block to a member, if there is one. */
export function withDoc(doc: string, member: string): string {
  return doc === "" ? member : `${doc}\n${member}`;
}
